### ISSUE TITLE
Could not find rasa_core: No module named converters

### ISSUE THREAD

**Issue by Brijeshlakkad** [Brijeshlakkad/Minor-Project#1]
**Operating System:** 
MacOS High Sierra -version 10.13.6
**rasa_core**
version - rasa-core-0.10.4
**rasa_nlu**
version - rasa-nlu-0.13.1

```
Traceback (most recent call last):
  File "nlu_model.py", line 12, in <module>
    from rasa_nlu.converters import load_data
ImportError: No module named converters
```

**Comment by Brijeshlakkad** [comment]
After running
`$ sudo pip install rasa_nlu==0.11.5 --user`
It gets working, but i get error when i run **training_init.py**
```
Using TensorFlow backend.
/Users/brijeshlakkad/Library/Python/2.7/lib/python/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
WARNING:rasa_core.agent:Passing a file name to `agent.train(...)` is deprecated. Rather load the data with `data = agent.load_data(file_name)` and pass it to `agent.train(data)`.
Traceback (most recent call last):
  File "training_init.py", line 20, in <module>
    validation_split = 0.2)
  File "/Users/brijeshlakkad/Library/Python/2.7/lib/python/site-packages/rasa_core/agent.py", line 262, in train
    training_trackers = self.load_data(training_trackers)
  File "/Users/brijeshlakkad/Library/Python/2.7/lib/python/site-packages/rasa_core/agent.py", line 232, in load_data
    debug_plots)
  File "/Users/brijeshlakkad/Library/Python/2.7/lib/python/site-packages/rasa_core/training/__init__.py", line 49, in load_data
    graph = extract_story_graph(resource_name, domain)
  File "/Users/brijeshlakkad/Library/Python/2.7/lib/python/site-packages/rasa_core/training/__init__.py", line 29, in extract_story_graph
    domain, interpreter)
  File "/Users/brijeshlakkad/Library/Python/2.7/lib/python/site-packages/rasa_core/training/dsl.py", line 144, in read_from_folder
    for f in nlu_utils.list_files(resource_name):
AttributeError: 'module' object has no attribute 'list_files'
```

**Comment by Brijeshlakkad** [comment]
Resolved

**Comment by Brijeshlakkad** [comment]
Resolved problem using:
`$ sudo pip install rasa_core==0.8.5 --user`
and 
`$ sudo pip install rasa_nlu==0.11.4 --user`
Both are compatible with each other
In addition to above error, you can get error of pypandoc:
 ```
OSError: No pandoc was found: either install pandoc and add it
    to your PATH or or call pypandoc.download_pandoc(...) or
    install pypandoc wheels with included pandoc.
```
To solve this, do this and run it using python:
```
from pypandoc.pandoc_download import download_pandoc
download_pandoc(version='1.19.1')
```
After this You can run easily above two cmd in Terminal.

**Comment by Brijeshlakkad** [comment]
Resolved problem using:
`$ sudo pip install rasa_core==0.8.5 --user`
and 
`$ sudo pip install rasa_nlu==0.11.4 --user`
Both are compatible with each other
In addition to above error, you can get error of pypandoc:
 ```
OSError: No pandoc was found: either install pandoc and add it
    to your PATH or or call pypandoc.download_pandoc(...) or
    install pypandoc wheels with included pandoc.
```
To solve this, do this and run it using python:
```
from pypandoc.pandoc_download import download_pandoc
download_pandoc(version='1.19.1')
```
After this You can run easily above two cmd in Terminal.
